---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 1m40s
  path: ./test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flask-app
